Differential/longhollow-apollos

apollos-church-api/config.yml
apollos-church-api/src/data/ContentItem.js
apollos-church-api/src/data/Vimeo.js
apollos-church-api/src/data/index.js
apolloschurchapp/src/theme/icons/Discover.js
apolloschurchapp/src/theme/icons/Heart.js
apolloschurchapp/src/theme/icons/Video.js

adds vimeo integration

---

apollos-church-api/src/data/ContentItem.js
apolloschurchapp/schema.graphql

add staff to content items

---

apollos-church-api/src/data/ContentItem.js
apollos-church-api/src/data/Matrix.js
apollos-church-api/src/data/index.js
apolloschurchapp/schema.graphql

add cta links

---

apollos-church-api/src/data/ContentItem.js
apolloschurchapp/schema.graphql

add campuses to content items

---

apollos-church-api/src/data/Algolia.js
apollos-church-api/src/data/ContentItem.js

More indicative of a group with a name and description versus just a collection of people. Plus it's the label Eric gave us.

changes staff field to ministry

---

apollos-church-api/src/data/Vimeo.js

feat: Cache vimeo responses

---

apollos-church-api/src/data/Person.js

Fetch staff through attributeValues

---

apollos-church-api/src/data/ContentItem.js

clients wants these fields to be simple text fields

replace fields on events

---

apollos-church-api/src/data/ContentItem.js
apollos-church-api/src/data/LiveStream.js
apollos-church-api/src/data/index.js
apolloschurchapp/schema.graphql

```
{
liveStreams {
eventStartTime
}
}
```

add future livestream dates

---

apollos-church-api/src/data/ContentItem.js

@lmommerts we can use this for the related news items in on the connect pages

get content by ministry type

---

apollos-church-api/load-tests/Apollos App Testing.jmx

chore: Configure load testing for Long Hollow

---

apollos-church-api/src/data/ContentItem.js

Web PR: https://github.com/Differential/longhollow-web/pull/31

Add showOnHomePage and featureOnHomePage

---

apollos-church-api/src/data/ContentItem.js

I need to add the seriesImage field to MediaContentItem and WeekendContentItem types in order to show the series image on pages with a hero video.

Add seriesImage to Media and Weekend items

---

apolloschurchapp/src/user-settings/index.js

added a divider below Change Password

---

apolloschurchapp/src/user-settings/index.js

chore: commented out support email

---

apollos-church-api/src/data/ContentItem.js

Closes [Add Background Series Image field](https://3.basecamp.com/3926363/buckets/22579289/todos/4293666077)
Adds a `seriesBackgroundImage` and `backgroundImage` for use on different content types. See https://github.com/Differential/longhollow-web/pull/41 for more

Series Background Image

---

apolloschurchapp/package.json
yarn.lock

chore: fixed crashing bug in check-in passes

---

apollos-church-api/config.yml

This adds a new channel to the home tab that is a HeroCardList containing the 5 most recent sermons.
https://user-images.githubusercontent.com/72768221/145472056-72858550-92bb-41fe-b078-8bc94f598cb5.mp4

feat: added a new recent sermon channel to home tab

---

apollos-church-api/src/data/ContentItem.js

Reverts Differential/longhollow-apollos#53

Revert "Update Sort for ContentItem and CTA Links"

---

apollos-church-api/src/data/ContentItem.js

Does the same thing as https://github.com/Differential/longhollow-apollos/pull/53, but reverses the start date/time sort to descending so newer stuff is on top.

Sort Content Items

---

apollos-church-api/src/data/Algolia.js

Adds the `last_name_asc` index back into the replicas array.

Add last_name_asc Index to Replicas
